import logo1 from "../Assets/cta-logo-one.svg";
import logo2 from "../Assets/cta-logo-two.png";
import favicon from "../Assets/favicon.svg";
import groupIcon from "../Assets/group-icon.png";
import homeBackground from "../Assets/home-background.png";
import homeIcon from "../Assets/home-icon.svg";
import loginBackground from '../Assets/login-background.jpg'
import logo from '../Assets/logo.svg'
import movieIcon from '../Assets/movie-icon.svg'
import originalIcon from '../Assets/original-icon.svg'
import playIconBlack from '../Assets/play-icon-black.png'
import playIconWhite from '../Assets/play-icon-white.png'
import react from '../Assets/react.svg'
import searchIcon from '../Assets/search-icon.svg'
import seriesIcon from '../Assets/series-icon.svg'
import slider1 from '../Assets/slider-badag.jpg'
import slider2 from '../Assets/slider-badging.jpg'
import slider3 from '../Assets/slider-scale.jpg'
import slider4 from '../Assets/slider-scales.jpg'
